export const jobOpeningsData = [
  {
    id: 1,
    department: "Human Resources",
    openings: [
      {
        title: "Recruiter",
        city: "Toronto",
        country: "Canada",
        salary: "$60,000 - $70,000",
        description: "Responsible for sourcing and interviewing candidates.",
        qualifications: ["Bachelor's degree", "HR", "2+ years experience"],
        role: "Full-time",
        applicationDeadline: "December 15, 2024",
      },
      {
        title: "HR Manager",
        city: "London",
        country: "UK",
        salary: "$90,000 - $100,000",
        description: "Oversee HR operations and manage employee relations.",
        qualifications: ["Bachelor's degree", "5+ years experience", "HR"],
        role: "Full-time",
        applicationDeadline: "January 10, 2025",
      },
    ],
  },
  {
    id: 2,
    department: "Marketing",
    openings: [
      {
        title: "Digital Marketing Specialist",
        city: "Sydney",
        country: "Australia",
        salary: "$70,000 - $90,000",
        description: "Develop and manage online marketing campaigns.",
        qualifications: [
          "Bachelor's degree",
          "Marketing",
          "3+ years experience",
        ],
        role: "Full-time",
        applicationDeadline: "November 30, 2024",
      },
      {
        title: "SEO Analyst",
        city: "Berlin",
        country: "Germany",
        salary: "$65,000 - $85,000",
        description: "Optimize website content for search engines.",
        qualifications: ["SEO tools", "Analytical skills"],
        role: "Full-time",
        applicationDeadline: "December 1, 2024",
      },
    ],
  },
  {
    id: 3,
    department: "Sales",
    openings: [
      {
        title: "Sales Representative",
        city: "Mexico City",
        country: "Mexico",
        salary: "$50,000 - $70,000",
        description: "Identify and pursue new sales opportunities.",
        qualifications: ["2+ years sales", "Communication skills"],
        role: "Full-time",
        applicationDeadline: "January 5, 2025",
      },
      {
        title: "Business Development Manager",
        city: "Tokyo",
        country: "Japan",
        salary: "$100,000+",
        description: "Drive new business initiatives and partnerships.",
        qualifications: ["5+ years experience", "Sales"],
        role: "Full-time",
        applicationDeadline: "December 20, 2024",
      },
    ],
  },
  {
    id: 4,
    department: "Information Technology",
    openings: [
      {
        title: "Software Developer",
        city: "Bangalore",
        country: "India",
        salary: "$100,000+",
        description: "Build and maintain web applications.",
        qualifications: ["React.js", "Node.js", "3+ years experience"],
        role: "Full-time",
        applicationDeadline: "January 15, 2025",
      },
      {
        title: "Cybersecurity Analyst",
        city: "Dublin",
        country: "Ireland",
        salary: "$80,000 - $100,000",
        description: "Protect company assets from cyber threats.",
        qualifications: ["Cybersecurity", "Certifications"],
        role: "Full-time",
        applicationDeadline: "December 25, 2024",
      },
    ],
  },
  {
    id: 5,
    department: "Finance",
    openings: [
      {
        title: "Financial Analyst",
        city: "Boston",
        country: "USA",
        salary: "$70,000 - $90,000",
        description: "Analyze financial data and forecasts.",
        qualifications: ["Bachelor's degree", "Finance", "2+ years experience"],
        role: "Full-time",
        applicationDeadline: "December 5, 2024",
      },
      {
        title: "Finance Manager",
        city: "Toronto",
        country: "Canada",
        salary: "$90,000 - $120,000",
        description:
          "Manage the finance team and report financial performance.",
        qualifications: ["5+ years finance", "Leadership skills"],
        role: "Full-time",
        applicationDeadline: "January 20, 2025",
      },
    ],
  },
  {
    id: 6,
    department: "Operations",
    openings: [
      {
        title: "Operations Manager",
        city: "Sydney",
        country: "Australia",
        salary: "$85,000 - $105,000",
        description: "Oversee daily operations and improve efficiency.",
        qualifications: ["Bachelor's degree", "5+ years operations"],
        role: "Full-time",
        applicationDeadline: "December 12, 2024",
      },
      {
        title: "Quality Assurance Analyst",
        city: "Cape Town",
        country: "South Africa",
        salary: "$60,000 - $80,000",
        description: "Ensure product quality through testing.",
        qualifications: ["QA", "Attention to detail"],
        role: "Full-time",
        applicationDeadline: "January 3, 2025",
      },
    ],
  },
  {
    id: 7,
    department: "Customer Service",
    openings: [
      {
        title: "Customer Support Representative",
        city: "Madrid",
        country: "Spain",
        salary: "$40,000 - $50,000",
        description: "Assist customers with inquiries and issues.",
        qualifications: ["Communication skills", "Support experience"],
        role: "Full-time",
        applicationDeadline: "December 30, 2024",
      },
      {
        title: "Client Relations Manager",
        city: "Paris",
        country: "France",
        salary: "$60,000 - $80,000",
        description: "Manage relationships with key clients.",
        qualifications: ["3+ years experience", "Client management"],
        role: "Full-time",
        applicationDeadline: "January 10, 2025",
      },
    ],
  },
  {
    id: 8,
    department: "Product Development",
    openings: [
      {
        title: "Product Manager",
        city: "Singapore",
        country: "Singapore",
        salary: "$100,000 - $120,000",
        description: "Lead product development from concept to launch.",
        qualifications: ["Product management", "Analytical skills"],
        role: "Full-time",
        applicationDeadline: "December 28, 2024",
      },
      {
        title: "Quality Control Inspector",
        city: "Amsterdam",
        country: "Netherlands",
        salary: "$50,000 - $70,000",
        description: "Inspect products for quality standards.",
        qualifications: ["Attention to detail", "QC experience"],
        role: "Full-time",
        applicationDeadline: "January 15, 2025",
      },
    ],
  },
  {
    id: 9,
    department: "Legal",
    openings: [
      {
        title: "Corporate Lawyer",
        city: "Dubai",
        country: "UAE",
        salary: "$120,000 - $150,000",
        description: "Provide legal advice to the company.",
        qualifications: ["JD degree", "Licensed to practice"],
        role: "Full-time",
        applicationDeadline: "December 10, 2024",
      },
      {
        title: "Compliance Officer",
        city: "Brussels",
        country: "Belgium",
        salary: "$90,000 - $110,000",
        description: "Ensure adherence to legal standards and regulations.",
        qualifications: ["Compliance", "Analytical skills"],
        role: "Full-time",
        applicationDeadline: "January 5, 2025",
      },
    ],
  },
  {
    id: 10,
    department: "Administrative",
    openings: [
      {
        title: "Office Manager",
        city: "Los Angeles",
        country: "USA",
        salary: "$60,000 - $80,000",
        description: "Oversee office operations and administration.",
        qualifications: ["3+ years office management", "Administration"],
        role: "Full-time",
        applicationDeadline: "January 2, 2025",
      },
      {
        title: "Executive Assistant",
        city: "Barcelona",
        country: "Spain",
        salary: "$55,000 - $75,000",
        description: "Support executives with administrative tasks.",
        qualifications: ["Executive assistant experience"],
        role: "Full-time",
        applicationDeadline: "December 22, 2024",
      },
    ],
  },
];
