const randomUserData = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    phone: "555-0123",
    resume: "https://example.com/resumes/alice-johnson.pdf",
    appliedPosition: "Software Engineer",
    status: "Scheduled",
    applicationDate: "2024-01-15",
    specialization: "Full Stack Development",
    profilePicture: "https://example.com/path/to/alice-profile-picture.jpg",
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    phone: "555-0456",
    resume: "https://example.com/resumes/bob-smith.pdf",
    appliedPosition: "Product Manager",
    status: "Reviewed",
    applicationDate: "2024-01-20",
    specialization: "Product Development",
    profilePicture: "https://example.com/path/to/bob-profile-picture.jpg",
  },
  {
    id: 3,
    name: "Cathy Lee",
    email: "cathy.lee@example.com",
    phone: "555-0789",
    resume: "https://example.com/resumes/cathy-lee.pdf",
    appliedPosition: "UX Designer",
    status: "Rejected",
    applicationDate: "2024-01-22",
    specialization: "User Experience",
    profilePicture: "https://picsum.photos/80/80",
  },
  {
    id: 4,
    name: "David Brown",
    email: "david.brown@example.com",
    phone: "555-1011",
    resume: "https://example.com/resumes/david-brown.pdf",
    appliedPosition: "Data Analyst",
    status: "Offered",
    applicationDate: "2024-01-25",
    specialization: "Data Science",
    profilePicture: "https://picsum.photos/80/80",
  },
  {
    id: 5,
    name: "Emma Wilson",
    email: "emma.wilson@example.com",
    phone: "555-1213",
    resume: "https://example.com/resumes/emma-wilson.pdf",
    appliedPosition: "Marketing Specialist",
    status: "Reviewing",
    applicationDate: "2024-01-30",
    specialization: "Marketing",
    profilePicture: "https://picsum.photos/80/80",
  },
  {
    id: 6,
    name: "Jack Wilson",
    email: "jack.wilson@example.com",
    phone: "555-1213",
    resume: "https://example.com/resumes/emma-wilson.pdf",
    appliedPosition: "Marketing Specialist",
    status: "Scheduled",
    applicationDate: "2024-01-30",
    specialization: "Marketing",
    profilePicture: "https://picsum.photos/80/80",
  },
];

export default randomUserData;
